name: Test RetroRadio Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configuración de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Paso 3: Instalación de dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Pruebas básicas
      - name: Run basic tests
        run: |
          echo "Verificando que las dependencias están instaladas..."
          python -c "import discord; import dotenv; import pydub; print('Pruebas básicas completadas.')"
